// Medicine datasets for LILNEST Medicine Guide
// Note: Dosage fields are placeholders for doctor entry only.

export const CATEGORIES = [
  "Fever",
  "Cold",
  "Nutrition",
  "Supplements",
  "Pain",
  "Skin",
  "Digestion",
  "Other",
];

export const FORMS = ["Tablet", "Syrup", "Drops", "Cream", "Ointment", "Inhaler", "Spray", "Powder", "Gel", "Capsule"];

// Color coding meta
export const META = {
  motherColor: "#FDECF4",
  babyColor: "#F8FBFF",
  lavender: "#F6F1FF",
  offwhite: "#FFFDFC",
  warningRed: "#FF6B6B",
  grey: "#6B7280",
};

// 30 Mother medicines (example dataset)
export const motherMedicines = [
  {
    id: "mom-1",
    name: "Prenatal Multivitamin",
    category: "Supplements",
    form: "Tablet",
    condition: "Maternal nutrition and fetal development",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Choose a prenatal with iron, iodine, and DHA.",
    precautions: [
      "Avoid megadose vitamins (A, E, K)",
      "Separate from thyroid meds by 4 hours",
    ],
    emergency_flags: ["Facial swelling", "Breathing difficulty", "Severe rash"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-2",
    name: "Folic Acid",
    category: "Supplements",
    form: "Tablet",
    condition: "Neural tube defect prevention",
    trimester_safety: "Preconception and T1",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "High-risk women may need 5 mg daily.",
    precautions: ["Do not replace B12 in deficiency"],
    emergency_flags: ["Severe rash", "Hives"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-3",
    name: "Iron (Ferrous Sulfate)",
    category: "Supplements",
    form: "Tablet",
    condition: "Anemia prevention/treatment",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Take with vitamin C; separate from calcium.",
    precautions: ["Constipation", "Nausea", "Dark stools"],
    emergency_flags: ["Severe abdominal pain", "Vomiting blood"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-4",
    name: "Calcium Carbonate",
    category: "Supplements",
    form: "Tablet",
    condition: "Bone health; antacid",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Split doses for absorption; avoid with iron within 2 hours.",
    precautions: ["Kidney stones history", "Hypercalcemia"],
    emergency_flags: ["Severe constipation", "Confusion"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-5",
    name: "Vitamin D3",
    category: "Supplements",
    form: "Tablet",
    condition: "Calcium absorption; immunity",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Check baseline 25(OH)D if at risk.",
    precautions: ["Avoid high-dose without labs"],
    emergency_flags: ["Severe vomiting", "Polyuria", "Confusion"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-6",
    name: "Omega-3 (DHA/EPA)",
    category: "Supplements",
    form: "Capsule",
    condition: "Fetal brain and eye development",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Prefer mercury-free fish oil; algae-based DHA is alternative.",
    precautions: ["Bleeding disorders", "Fish allergy"],
    emergency_flags: ["Anaphylaxis", "Severe hives"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-7",
    name: "Paracetamol (Acetaminophen)",
    category: "Fever",
    form: "Tablet",
    condition: "Fever and mild pain",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Use minimal effective duration.",
    precautions: ["Liver disease", "Avoid duplicate combo products"],
    emergency_flags: ["Jaundice", "Severe abdominal pain", "Overdose"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-8",
    name: "Doxylamine + Vitamin B6",
    category: "Digestion",
    form: "Tablet",
    condition: "Nausea and vomiting of pregnancy",
    trimester_safety: "T1/T2/T3",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "First-line for morning sickness.",
    precautions: ["Sedation", "Avoid driving initially"],
    emergency_flags: ["Severe drowsiness", "Allergic reaction"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-9",
    name: "Ondansetron",
    category: "Digestion",
    form: "Tablet",
    condition: "Hyperemesis gravidarum",
    trimester_safety: "Use if benefits outweigh risks",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Consider ECG if QT risk.",
    precautions: ["Constipation", "Headache", "QT prolongation risk"],
    emergency_flags: ["Palpitations", "Syncope"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-10",
    name: "Metoclopramide",
    category: "Digestion",
    form: "Tablet",
    condition: "Nausea and reflux",
    trimester_safety: "All trimesters (short-term)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Limit duration to reduce EPS risk.",
    precautions: ["Dystonia", "Parkinsonism", "Restlessness"],
    emergency_flags: ["Involuntary movements", "Severe agitation"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-11",
    name: "Labetalol",
    category: "Other",
    form: "Tablet",
    condition: "Hypertension in pregnancy",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Monitor BP and fetal growth.",
    precautions: ["Asthma", "Bradycardia"],
    emergency_flags: ["Severe dizziness", "Fainting"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-12",
    name: "Methyldopa",
    category: "Other",
    form: "Tablet",
    condition: "Hypertension in pregnancy",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "May cause sedation.",
    precautions: ["Depression", "Liver disease"],
    emergency_flags: ["Jaundice", "Severe fatigue"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-13",
    name: "Nifedipine (ER)",
    category: "Other",
    form: "Tablet",
    condition: "Hypertension or tocolysis",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Avoid immediate-release for chronic use.",
    precautions: ["Headache", "Flushing", "Edema"],
    emergency_flags: ["Severe hypotension", "Chest pain"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-14",
    name: "Metformin",
    category: "Other",
    form: "Tablet",
    condition: "Gestational diabetes",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Take with meals to reduce GI upset.",
    precautions: ["Renal impairment", "Diarrhea"],
    emergency_flags: ["Lactic acidosis symptoms"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-15",
    name: "Insulin (basal/bolus)",
    category: "Other",
    form: "Injection",
    condition: "Diabetes in pregnancy",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Education on hypoglycemia management required.",
    precautions: ["Hypoglycemia"],
    emergency_flags: ["Confusion", "Seizures", "Unresponsiveness"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-16",
    name: "Levothyroxine",
    category: "Other",
    form: "Tablet",
    condition: "Hypothyroidism",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Take fasting; separate calcium/iron 4 hours.",
    precautions: ["Overreplacement leads to palpitations"],
    emergency_flags: ["Chest pain", "Severe palpitations"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-17",
    name: "Progesterone (vaginal/oral)",
    category: "Other",
    form: "Capsule",
    condition: "Recurrent miscarriage/short cervix",
    trimester_safety: "Per specialist",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Vaginal route often preferred.",
    precautions: ["Drowsiness", "Breast tenderness"],
    emergency_flags: ["Severe headache", "Vision changes"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-18",
    name: "Low‑Dose Aspirin",
    category: "Other",
    form: "Tablet",
    condition: "Preeclampsia risk reduction",
    trimester_safety: "Start before 16 weeks; stop ~36 weeks",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Only on doctor advice for high-risk.",
    precautions: ["Bleeding disorders", "Ulcer disease"],
    emergency_flags: ["Bleeding", "Black stools"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-19",
    name: "Docusate Sodium",
    category: "Digestion",
    form: "Capsule",
    condition: "Constipation (stool softener)",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Increase fluids and fiber.",
    precautions: ["Abdominal cramps"],
    emergency_flags: ["Rectal bleeding"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-20",
    name: "Lactulose",
    category: "Digestion",
    form: "Syrup",
    condition: "Constipation (osmotic)",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "May cause gas/bloating initially.",
    precautions: ["Diabetes (sugar content)"],
    emergency_flags: ["Severe abdominal pain"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-21",
    name: "Hydrocortisone 1%",
    category: "Skin",
    form: "Cream",
    condition: "Eczema/dermatitis (localized)",
    trimester_safety: "All trimesters (short term)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Avoid prolonged/high‑potency steroids.",
    precautions: ["Skin thinning with prolonged use"],
    emergency_flags: ["Infection signs", "Worsening rash"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-22",
    name: "Clotrimazole Vaginal Cream",
    category: "Skin",
    form: "Cream",
    condition: "Candidiasis",
    trimester_safety: "Avoid T1 if possible",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "7‑day course preferred in pregnancy.",
    precautions: ["Local irritation"],
    emergency_flags: ["Severe burning", "Allergy"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-23",
    name: "Nitrofurantoin",
    category: "Other",
    form: "Capsule",
    condition: "Urinary tract infection",
    trimester_safety: "Avoid near term (G6PD)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Use per culture sensitivity.",
    precautions: ["G6PD deficiency", "Late T3 caution"],
    emergency_flags: ["Breathlessness", "Chest pain"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-24",
    name: "Amoxicillin‑Clavulanate",
    category: "Other",
    form: "Tablet",
    condition: "Bacterial infections",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Take with food; complete course.",
    precautions: ["Penicillin allergy"],
    emergency_flags: ["Anaphylaxis", "Severe rash"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-25",
    name: "Azithromycin",
    category: "Other",
    form: "Tablet",
    condition: "Respiratory/urinary infections",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Once‑daily dosing; complete course.",
    precautions: ["Liver disease", "QT prolongation"],
    emergency_flags: ["Palpitations", "Severe diarrhea"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-26",
    name: "Saline Nasal Spray",
    category: "Cold",
    form: "Spray",
    condition: "Nasal congestion",
    trimester_safety: "All trimesters",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Non‑medicated; safe supportive care.",
    precautions: ["Maintain hygiene of nozzle"],
    emergency_flags: ["Nosebleeds (frequent)", "Severe pain"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "mom-27",
    name: "Famotidine",
    category: "Digestion",
    form: "Tablet",
    condition: "GERD/Heartburn",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Use after lifestyle measures.",
    precautions: ["Renal dose adjustment"],
    emergency_flags: ["Black stools", "Severe abdominal pain"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-28",
    name: "Polyethylene Glycol (PEG)",
    category: "Digestion",
    form: "Powder",
    condition: "Constipation (osmotic)",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Dissolve in water; titrate to effect.",
    precautions: ["Electrolyte imbalance with overuse"],
    emergency_flags: ["Persistent diarrhea", "Dehydration"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-29",
    name: "Topical Mupirocin",
    category: "Skin",
    form: "Ointment",
    condition: "Localized bacterial skin infection",
    trimester_safety: "All trimesters (localized)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Use thin film; avoid eyes.",
    precautions: ["Allergy to components"],
    emergency_flags: ["Spreading redness", "Fever"],
    safety_level: "Doctor Required",
  },
  {
    id: "mom-30",
    name: "Magnesium Oxide",
    category: "Supplements",
    form: "Tablet",
    condition: "Leg cramps/deficiency (per doctor)",
    trimester_safety: "All trimesters (per doctor)",
    doctor_required: true,
    dose_mg: null,
    frequency: null,
    duration: null,
    notes: "Consider only if deficient.",
    precautions: ["Diarrhea", "Renal impairment"],
    emergency_flags: ["Severe weakness", "Irregular heartbeat"],
    safety_level: "Doctor Required",
  },
];

// 30 Baby/Child medicines (example dataset)
export const babyMedicines = [
  {
    id: "baby-1",
    name: "Paracetamol (Acetaminophen)",
    category: "Fever",
    form: "Syrup",
    condition: "Fever and pain relief",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: true,
    frequency: null,
    duration: null,
    notes: "Weight‑based dosing only by doctor.",
    precautions: ["Liver disease", "Avoid duplicate combo products"],
    emergency_flags: ["Rash", "Breathing difficulty", "Persistent vomiting"],
    safety_level: "Age‑Restricted",
  },
  {
    id: "baby-2",
    name: "Ibuprofen",
    category: "Pain",
    form: "Syrup",
    condition: "Fever, pain, inflammation",
    minimum_age: "6m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: true,
    frequency: null,
    duration: null,
    notes: "Give with food; avoid if dehydrated.",
    precautions: ["Kidney issues", "Ulcer disease"],
    emergency_flags: ["Blood in stool", "Severe vomiting"],
    safety_level: "Age‑Restricted",
  },
  {
    id: "baby-3",
    name: "Cetirizine",
    category: "Cold",
    form: "Syrup",
    condition: "Allergic rhinitis/itching",
    minimum_age: "6m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "May cause drowsiness in some children.",
    precautions: ["Severe kidney disease"],
    emergency_flags: ["Severe rash", "Swelling"],
    safety_level: "Age‑Restricted",
  },
  {
    id: "baby-4",
    name: "Loratadine",
    category: "Cold",
    form: "Syrup",
    condition: "Allergies (non‑drowsy)",
    minimum_age: "2y",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Daytime antihistamine.",
    precautions: ["Liver disease"],
    emergency_flags: ["Hives", "Breathing difficulty"],
    safety_level: "Age‑Restricted",
  },
  {
    id: "baby-5",
    name: "Saline Nasal Drops",
    category: "Cold",
    form: "Drops",
    condition: "Nasal congestion",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Supportive care; safe at all ages.",
    precautions: ["Use sterile saline only"],
    emergency_flags: ["Frequent nosebleeds"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "baby-6",
    name: "Simethicone Drops",
    category: "Digestion",
    form: "Drops",
    condition: "Infant gas/colic",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Use after feeds as advised.",
    precautions: ["Intestinal obstruction"],
    emergency_flags: ["Persistent vomiting", "Abdominal distension"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-7",
    name: "Oral Rehydration Solution (ORS)",
    category: "Digestion",
    form: "Solution",
    condition: "Dehydration due to diarrhea/vomiting",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: true,
    frequency: null,
    duration: null,
    notes: "Small frequent sips; continue breastfeeding.",
    precautions: ["Severe dehydration needs hospital"],
    emergency_flags: ["Lethargy", "Sunken eyes", "No urine >8h"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-8",
    name: "Zinc Sulfate",
    category: "Digestion",
    form: "Syrup",
    condition: "Acute diarrhea",
    minimum_age: "6m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "10–14 days course per doctor.",
    precautions: ["Nausea"],
    emergency_flags: ["Persistent vomiting"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-9",
    name: "Probiotic Drops",
    category: "Digestion",
    form: "Drops",
    condition: "Gut health; diarrhea prevention",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Use trusted brands; follow doctor dosing.",
    precautions: ["Immunocompromised caution"],
    emergency_flags: ["Fever", "Worsening diarrhea"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-10",
    name: "Amoxicillin",
    category: "Other",
    form: "Syrup",
    condition: "Bacterial infections (per culture)",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: true,
    frequency: null,
    duration: null,
    notes: "Complete full course; store suspension properly.",
    precautions: ["Penicillin allergy"],
    emergency_flags: ["Severe rash", "Breathing difficulty"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-11",
    name: "Cephalexin",
    category: "Other",
    form: "Syrup",
    condition: "Skin/respiratory infections",
    minimum_age: "1m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: true,
    frequency: null,
    duration: null,
    notes: "Complete course; refrigeration often required.",
    precautions: ["Cephalosporin allergy"],
    emergency_flags: ["Severe diarrhea", "Rash"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-12",
    name: "Azithromycin",
    category: "Other",
    form: "Syrup",
    condition: "Respiratory/ear infections",
    minimum_age: "6m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: true,
    frequency: null,
    duration: null,
    notes: "Once‑daily dosing; follow schedule.",
    precautions: ["Liver disease", "QT risk"],
    emergency_flags: ["Palpitations"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-13",
    name: "Mebendazole",
    category: "Other",
    form: "Chewable",
    condition: "Intestinal worms",
    minimum_age: "1y",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Hygiene for entire family; repeat as advised.",
    precautions: ["Liver disease"],
    emergency_flags: ["Severe abdominal pain"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-14",
    name: "Hydrocortisone 1%",
    category: "Skin",
    form: "Cream",
    condition: "Eczema/rash",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Short courses; avoid face unless advised.",
    precautions: ["Skin thinning with overuse"],
    emergency_flags: ["Infection signs"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-15",
    name: "Clotrimazole Cream",
    category: "Skin",
    form: "Cream",
    condition: "Fungal diaper rash",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Keep area dry; continue few days after clear.",
    precautions: ["Local irritation"],
    emergency_flags: ["Worsening redness"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "baby-16",
    name: "Petroleum Jelly",
    category: "Skin",
    form: "Ointment",
    condition: "Diaper rash prevention",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Barrier layer at each diaper change.",
    precautions: ["External use only"],
    emergency_flags: ["Allergy"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "baby-17",
    name: "Erythromycin Eye Ointment",
    category: "Skin",
    form: "Ointment",
    condition: "Bacterial conjunctivitis",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Wash hands; avoid sharing towels.",
    precautions: ["Blurred vision after application"],
    emergency_flags: ["Eye swelling", "Severe redness"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-18",
    name: "Glycerin Suppository (Infant)",
    category: "Digestion",
    form: "Suppository",
    condition: "Constipation (rescue)",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Occasional use; address diet/hydration.",
    precautions: ["Rectal irritation"],
    emergency_flags: ["Rectal bleeding"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-19",
    name: "Vitamin D3 Drops",
    category: "Supplements",
    form: "Drops",
    condition: "Bone development",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Recommended for breast‑fed infants.",
    precautions: ["Avoid overdosing"],
    emergency_flags: ["Vomiting", "Constipation"] ,
    safety_level: "Doctor Required",
  },
  {
    id: "baby-20",
    name: "Iron (Ferrous) Syrup",
    category: "Supplements",
    form: "Syrup",
    condition: "Iron deficiency anemia",
    minimum_age: "6m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: true,
    frequency: null,
    duration: null,
    notes: "Give with vitamin C; may stain teeth.",
    precautions: ["Constipation", "Dark stools"],
    emergency_flags: ["Vomiting", "Abdominal pain"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-21",
    name: "Calcium + Vitamin D Syrup",
    category: "Supplements",
    form: "Syrup",
    condition: "Bone growth",
    minimum_age: "6m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Per doctor if dietary intake is low.",
    precautions: ["Constipation"],
    emergency_flags: ["Vomiting", "Irritability"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-22",
    name: "Salbutamol Inhaler (with spacer)",
    category: "Other",
    form: "Inhaler",
    condition: "Wheezing/asthma relief",
    minimum_age: "1y",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Use spacer/mask; rinse mouth after use.",
    precautions: ["Tremor", "Tachycardia"],
    emergency_flags: ["Fast breathing", "Lips turning blue"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-23",
    name: "Chlorpheniramine",
    category: "Cold",
    form: "Syrup",
    condition: "Allergies/cold (sedating)",
    minimum_age: "2y",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Causes drowsiness; nighttime dosing.",
    precautions: ["Avoid with other sedatives"],
    emergency_flags: ["Breathing difficulty"],
    safety_level: "Age‑Restricted",
  },
  {
    id: "baby-24",
    name: "Topical Zinc Oxide",
    category: "Skin",
    form: "Cream",
    condition: "Diaper rash barrier",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Apply thick layer as barrier.",
    precautions: ["External use only"],
    emergency_flags: ["Allergic rash"],
    safety_level: "Pregnancy Safe",
  },
  {
    id: "baby-25",
    name: "Nystatin Oral Suspension",
    category: "Skin",
    form: "Syrup",
    condition: "Oral thrush",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Apply to mouth surfaces after feeds.",
    precautions: ["Stop if rash/worsening"],
    emergency_flags: ["Facial swelling"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-26",
    name: "Acetylcysteine",
    category: "Cold",
    form: "Syrup",
    condition: "Thick mucus (per doctor)",
    minimum_age: "2y",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: true,
    frequency: null,
    duration: null,
    notes: "Use only under pediatric advice.",
    precautions: ["Bronchospasm in asthmatics"],
    emergency_flags: ["Wheezing", "Breathlessness"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-27",
    name: "Polio Vaccine (OPV)",
    category: "Other",
    form: "Drops",
    condition: "Immunization per schedule",
    minimum_age: "0m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Follow national schedule.",
    precautions: ["Immunodeficiency"],
    emergency_flags: ["High fever", "Severe allergy"],
    safety_level: "Doctor Required",
  },
  {
    id: "baby-28",
    name: "ORS + Zinc Kit",
    category: "Digestion",
    form: "Solution",
    condition: "Diarrhea management kit",
    minimum_age: "6m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: true,
    frequency: null,
    duration: null,
    notes: "Combination per pediatric advice.",
    precautions: ["Persistent blood in stool"],
    emergency_flags: ["Lethargy", "No urine"] ,
    safety_level: "Doctor Required",
  },
  {
    id: "baby-29",
    name: "Sunscreen (Mineral, SPF 30)",
    category: "Skin",
    form: "Cream",
    condition: "Sun protection (6m+)",
    minimum_age: "6m",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Broad‑spectrum mineral sunscreen for infants 6m+.",
    precautions: ["Avoid around eyes"],
    emergency_flags: ["Severe rash"],
    safety_level: "Age‑Restricted",
  },
  {
    id: "baby-30",
    name: "Honey (Cough Soothing)",
    category: "Cold",
    form: "Syrup",
    condition: "Cough soothing (natural)",
    minimum_age: "1y",
    doctor_required: true,
    dose_ml: null,
    dose_drops: null,
    weight_required: false,
    frequency: null,
    duration: null,
    notes: "Never give honey under 1 year (botulism risk).",
    precautions: ["Dental hygiene after use"],
    emergency_flags: ["Wheezing", "Persistent fever"],
    safety_level: "Age‑Restricted",
  },
];
